# .readthedocs.yaml
version: 2
build:
  os: ubuntu-22.04
  tools:
    python: "3.11"

# Sphinxの設定を有効にし、conf.pyの場所を指定
sphinx:
  configuration: docs/conf.py

# 依存関係のインストールを指示
python:
  install:
    - requirements: requirements.txt
