project = 'YU1000-docs'
copyright = '2025, YU1000'
author = 'YU1000'
extensions = []
templates_path = ['_templates']
exclude_patterns = ['_build', 'Thumbs.db', '.DS_Store']
language = 'ja'
html_theme = 'sphinx_rtd_theme'
html_static_path = ['_static']
